### ISSUE TITLE
Suppress warning on @ddradar/client test

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddradar#680]
Vue warns on [SearchBox component test](https://github.com/ddradar/ddradar/blob/master/client/__tests__/components/pages/SearchBox.test.ts)
```console
PASS Client __tests__/components/pages/SearchBox.test.ts
  ● Console

    console.error
      [Vue warn]: Unknown custom element: <b-autocomplete> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <SearchBoxComponent>
             <Root>

      at warn (../node_modules/vue/dist/vue.common.dev.js:630:15)
      at createElm (../node_modules/vue/dist/vue.common.dev.js:5973:11)
      at VueComponent.__patch__ (../node_modules/vue/dist/vue.common.dev.js:6510:7)
      at VueComponent._update (../node_modules/vue/dist/vue.common.dev.js:3957:19)
      at VueComponent.call (../node_modules/vue/dist/vue.common.dev.js:4078:10)
      at Watcher.get (../node_modules/vue/dist/vue.common.dev.js:4490:25)
      at new Watcher (../node_modules/vue/dist/vue.common.dev.js:4479:12)
      at mountComponent (../node_modules/vue/dist/vue.common.dev.js:4085:3)
      at VueComponent.call (../node_modules/vue/dist/vue.common.dev.js:9084:10)
      at VueComponent.$mount (../node_modules/vue/dist/vue.common.dev.js:11989:16)
      at i (../node_modules/vue/dist/vue.common.dev.js:3140:13)
      at createComponent (../node_modules/vue/dist/vue.common.dev.js:6013:9)
      at createElm (../node_modules/vue/dist/vue.common.dev.js:5960:9)
      at VueComponent.patch [as __patch__] (../node_modules/vue/dist/vue.common.dev.js:6510:7)
```

**Comment by nogic1008** [comment]
fixed in #657
